/*
 * darwin-code-backend
 *
 * darwin-code-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExternalPullRequestResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "assistant_turn_id")]
    pub assistant_turn_id: String,
    #[serde(rename = "pull_request")]
    pub pull_request: Box<models::GitPullRequest>,
    #[serde(
        rename = "darwin_code_updated_sha",
        skip_serializing_if = "Option::is_none"
    )]
    pub darwin_code_updated_sha: Option<String>,
}

impl ExternalPullRequestResponse {
    pub fn new(
        id: String,
        assistant_turn_id: String,
        pull_request: models::GitPullRequest,
    ) -> ExternalPullRequestResponse {
        ExternalPullRequestResponse {
            id,
            assistant_turn_id,
            pull_request: Box::new(pull_request),
            darwin_code_updated_sha: None,
        }
    }
}
